server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  h2:
    console.enabled: true
  liquibase:
    drop-first: false
    default-schema: public
    enabled: false
    change-log: classpath:/db/changelog/db-changelog-master.xml
    url: ${spring.datasource.url}
    driverClassName: ${spring.datasource.driverClassName}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}